### ISSUE TITLE
great simple module!

### ISSUE THREAD

**Issue by dodds-steven** [manuelVo/foundryvtt-smart-doors#37]
hope to see this one made compatible with 11 and 12.  right now it seems to work mostly, but when you edit a door the settings are not remembered?

it could be a conflict with another mod, but I don't think so, I think its a Hook issue in 11

typeError: Error thrown in hooked function 'onRederWallConfig' for hook 'renderWallConfig'. Cannot read properties of undefined (reading 'flags')
[Detected 1 package: smart-doors]
    at Object.onRederWallConfig [as fn] (synchronized_doors.js:25:38)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at WallConfig._render (foundry.js:5855:13)
    at async WallConfig._render (foundry.js:6532:5)

**Comment by farling42** [comment]
No errors reported in v1.5.0
